import { DataProvider } from "@/DataContext";
import StyledComponentsRegistry from "./lib/registry";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <head>
          <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Joan:wght@400&display=swap');
          html, body {
            padding: 0;
            margin: 0;
            font-family: 'Joan', sans-serif;
            box-sizing: border-box;
          }
          *, *::before, *::after {
            box-sizing: border-box;
          }
        `}</style>
        </head>
        <body style={{ padding: 0, margin: 0 }}>
          <DataProvider>
            <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
          </DataProvider>
        </body>
      </html>
    </>
  );
}
